user1=int(input("Enter 1st number to print:\n"))
user2=int(input("Enter 2nd number to print:\n"))
user3=int(input("Enter 3rd number to print:\n"))
user4=int(input("Enter 4th number to print:\n"))
user5=int(input("Enter 5th number to print:\n"))
user6=int(input("Enter 6th number to print:\n"))
user7=int(input("Enter 7th number to print:\n"))
user8=int(input("Enter 8th number to print:\n"))
num={user1,user2,user3, user4, user5, user6, user7, user8}
print("From the input numbers the unique numbers are: ",num)